---
all:
  hosts:
    el-instance:
      ansible_host: 62.84.123.1
    k-instance:
      ansible_host: 62.84.123.217
    application-instance:
      ansible_host: 51.250.23.231
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    k-instance:
app:
  hosts:
    application-instance:
